### PR TITLE
add g:gen_tags#scm_list for modify scm_list

### PR DESCRIPTION
**Pull request by fcying**
the default scm_list is not enough

### CODE REVIEW

**Comment by jsfaint** [comment]
I'm a little curious which scm do you use? 😄

**Comment by fcying** [comment]
I have some big git directories, if gentag directly, it will takes a lot of time and gen  a lot of unused content, so I mk a dir `.root` for some alone project in it.

**Comment by jsfaint** [comment]
@fcying 
Sorry, I think it's a little over to add a new option for this requirement.
You can just add a directory named as `.git` to achieve your requirement.

**Comment by fcying** [comment]
Because the compile script will search the scm directory, if use the existing one, I need to add `.svn` in the git directory, add  `.git` in the svn directory... it is easy to get confused, so I added a custom directory.

**Comment by jsfaint** [comment]
I understand your concern.
Maybe we should just make it as standard behavior but not add a new option.

I prefer to just extend the `l:scm`.

```diff
- let l:scm_list = ['.git', '.hg', '.svn']
+ let l:scm_list = ['.root', '.git', '.hg', '.svn']
```

**Comment by fcying** [comment]
I added an option just for not modify the original scm_list, then I can add `.root` in my vimrc.

I modify it in `l:scm_list` now.

**Comment by jsfaint** [comment]
Merged. Thanks for the PR~

**Pull request merged**
