### PR TITLE
add ncm2 source support

### PR DESCRIPTION
**Pull request by fcying**
for ncm2 https://github.com/ncm2/ncm2  #61

### CODE REVIEW

**Comment by jsfaint** [comment]
I tested this PR, it works for me 👍 
But there are several minor things:
1. Please rename the file `ncm2_gen_tags` as `ncm2_gtags`, because this is only gtags completion.
2. Please remove trailing space in `ncm2_gen_tags.py` line 30

Thanks for your contribution!

BTW: Should we remove ncm source now? or just keep it for compatible.

**Comment by fcying** [comment]
I think it can be remove now.....

The maintainer said:
```
PLEASE USE https://github.com/ncm2/ncm2 INSTEAD
```

**Comment by jsfaint** [comment]
OK, please remove it with a new commit.
I'll modify the document later when I get some time.

A little question why do you add `cwd=data['cwd']` for `subprocess.Popen()`?
I removed this line, the source still works.
Just curious, because I'm not familiar with python 😄

**Comment by fcying** [comment]
It will changes the `global` working dir to cwd before subprocess executing the child, may be it will effect the relative position for some files? 
I just saw it add in deoplete source, so I add it too@_@

**Comment by jsfaint** [comment]
`gtags`/`global` checks the database via environment variable `GTAGSDBPATH`, but not in the current working directory
So maybe we can remove it?

**Comment by fcying** [comment]
Ok, I remove it both ncm2 and deoplete source.

**Comment by jsfaint** [comment]
Merged, thanks for your contribution~

**Comment by butterflyfish** [comment]
if possible, please help add function parameter expansion support. appreciated.

**Comment by jsfaint** [comment]
gtags is tag based only, it is impossible to add parameter expansion support...

**Comment by butterflyfish** [comment]
GNU global provide function prototype, that's why I think it's impossible. Like [ncm2/ncm2-pyclang](https://github.com/ncm2/ncm2-pyclang) provide parameter expansion.

example:
```
global -x new_terminal
new_terminal      113 src/terminal.c   new_terminal(tea_t* tea, char* name, int ifd, int ofd, aio_recv_t aio_recv)
```

**Comment by jsfaint** [comment]
Yes, but it is not for completion. I have no idea how to implement it.
The PR is appreciated.

**Comment by butterflyfish** [comment]
I'm not python programmer, no idea also. Welcome someone implement this fantastic feature.

**Pull request merged**
